apiVersion: v1
kind: Namespace
metadata:
  name: ${APPLICATION_NAMESPACE}
  labels:
    name: ${APPLICATION_NAMESPACE}

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ${APPLICATION_SERVICE_ACCOUNT_NAME}
  namespace: ${APPLICATION_NAMESPACE}
  annotations:
    eks.amazonaws.com/role-arn: ${IRSA_IAM_ROLE_ARN}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${APPLICATION_NAME}-deployment
  labels:
    app: ${APPLICATION_NAME}
  namespace: ${APPLICATION_NAMESPACE}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ${APPLICATION_NAME}
  template:
    metadata:
      labels:
        app: ${APPLICATION_NAME}
    spec:
      # Required to read AWS account token
      serviceAccountName: ${APPLICATION_SERVICE_ACCOUNT_NAME}
      containers:
      - image: ${DOCKER_HUB_USERNAME}/${APPLICATION_NAME}:latest
        name: ${APPLICATION_NAME}
        ports:
        - containerPort: 5000
        resources: {}
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: APP_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.labels['app']
        securityContext:
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 1001
